// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleSmtpInterceptor.Data;

namespace SimpleSmtpInterceptor.Data.Migrations
{
    [DbContext(typeof(InterceptorModel))]
    [Migration("20191101001815_AddedLogging")]
    partial class AddedLogging
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleSmtpInterceptor.Data.Entities.Email", b =>
                {
                    b.Property<long>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<string>("Message")
                        .IsRequired();

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(78)
                        .IsUnicode(false);

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.HasKey("EmailId")
                        .HasName("PK_dbo.Email_EmailId");

                    b.ToTable("Email","dbo");
                });

            modelBuilder.Entity("SimpleSmtpInterceptor.Data.Entities.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Callsite")
                        .HasMaxLength(300)
                        .IsUnicode(true);

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Exception")
                        .IsUnicode(true);

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<string>("Logger")
                        .HasMaxLength(300)
                        .IsUnicode(true);

                    b.Property<string>("MachineName")
                        .HasMaxLength(200)
                        .IsUnicode(true);

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(true);

                    b.Property<string>("Properties")
                        .IsUnicode(true);

                    b.HasKey("LogId")
                        .HasName("PK_dbo.Log_LogId");

                    b.ToTable("Log","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
